// <auto-generated />
using System;
using KoloTumak.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KoloTumak.Data.Migrations
{
    [DbContext(typeof(KoloTumakContext))]
    [Migration("20220421180423_m2")]
    partial class m2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("KoloTumak.Data.Data.CMS.About", b =>
                {
                    b.Property<int>("IdAbout")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAbout"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAbout");

                    b.ToTable("About");
                });

            modelBuilder.Entity("KoloTumak.Data.Data.CMS.EventsAllUser", b =>
                {
                    b.Property<int>("IdEvents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEvents"), 1L, 1);

                    b.Property<int>("Contact")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateStart")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("NameSurnameResponsiblePerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEvents");

                    b.ToTable("EventsAllUser");
                });

            modelBuilder.Entity("KoloTumak.Data.Data.CMS.HuntersList", b =>
                {
                    b.Property<int>("IdHunters")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHunters"), 1L, 1);

                    b.Property<int>("Contact")
                        .HasColumnType("int");

                    b.Property<int>("HuntingBookIdHunting")
                        .HasColumnType("int");

                    b.Property<int>("IdHunting")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdHunters");

                    b.HasIndex("HuntingBookIdHunting");

                    b.ToTable("HuntersList");
                });

            modelBuilder.Entity("KoloTumak.Data.Data.CMS.HuntingBook", b =>
                {
                    b.Property<int>("IdHunting")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHunting"), 1L, 1);

                    b.Property<string>("AuthorizationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateHuntingEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateHuntingStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("NamePlace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdHunting");

                    b.ToTable("HuntingBook");
                });

            modelBuilder.Entity("KoloTumak.Data.Data.CMS.Main", b =>
                {
                    b.Property<int>("IdStrony")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStrony"), 1L, 1);

                    b.Property<string>("Contents")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("LinkName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("IdStrony");

                    b.ToTable("Main");
                });

            modelBuilder.Entity("KoloTumak.Data.Data.CMS.News", b =>
                {
                    b.Property<int>("IdNews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNews"), 1L, 1);

                    b.Property<string>("Contents")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("DateStart")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPosition")
                        .HasColumnType("int");

                    b.Property<string>("NameSurnameAdd")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdNews");

                    b.ToTable("News");
                });

            modelBuilder.Entity("KoloTumak.Data.Data.CMS.HuntersList", b =>
                {
                    b.HasOne("KoloTumak.Data.Data.CMS.HuntingBook", "HuntingBook")
                        .WithMany("Hunter")
                        .HasForeignKey("HuntingBookIdHunting")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HuntingBook");
                });

            modelBuilder.Entity("KoloTumak.Data.Data.CMS.HuntingBook", b =>
                {
                    b.Navigation("Hunter");
                });
#pragma warning restore 612, 618
        }
    }
}
